package feedbuilder

// Generate the repo.pub + add.sh helper files.
//
// One installer script is generated per declared point release, pinned to that
// release: <release>/add.sh inside each release directory, next to targets/.
// The public keys sit at the output root: repo.pub (usign, opkg branches) and
// repo-apk.pem (EC, apk branches). The script detects the device's
// architecture, target and exact kernel on its own, installs the signing key,
// and adds only the feeds that actually exist for that device — as src/gz
// lines in /etc/opkg/customfeeds.conf up to 24.10, as packages.adb URLs in
// /etc/apk/repositories.d/customfeeds.list from 25.12 on.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// apkPubName is the served apk public key (next to repo.pub).
const apkPubName = "repo-apk.pem"

const addSHTemplate = `#!/bin/sh
# Auto-generated by openwrt-feed-builder. Adds this custom feed for THIS device,
# pinned to release @RELEASE@. The feed mirrors the
# downloads.openwrt.org/releases/ layout.
#
# On the router:
#   wget -qO- BASE_URL/@RELEASE@/add.sh | sh
# or with an explicit base URL:
#   wget -qO- .../add.sh | BASE_URL=https://my.host sh
set -e

BASE_URL="${BASE_URL:-@BASE_URL@}"
BRANCH="@BRANCH@"
RELEASE="@RELEASE@"
KEYID="@KEYID@"
SIGNED="@SIGNED@"

# shellcheck disable=SC1091 # the device's release file, present at runtime
[ -r /etc/openwrt_release ] && . /etc/openwrt_release
ARCH="$DISTRIB_ARCH"
[ -n "$ARCH" ] || { echo "cannot detect DISTRIB_ARCH (is this OpenWrt?)"; exit 1; }
[ -z "$DISTRIB_RELEASE" ] || [ "$DISTRIB_RELEASE" = "$RELEASE" ] || \
  echo "warning: device runs $DISTRIB_RELEASE but this feed is for $RELEASE"

# Exact kernel this device runs, from the installed kernel package. Its version
# "6.6.141~<hash>-r1" becomes the kmods/<kernel>/ directory name
# "6.6.141-1-<hash>", same convention as the official kmods feed.
KERNEL=$(sed -n '/^Package: kernel$/,/^$/s/^Version: *//p' /usr/lib/opkg/status 2>/dev/null | head -n 1)
case "$KERNEL" in
  *~*) KERNEL=$(echo "$KERNEL" | sed 's/^\(.*\)~\([0-9a-f]*\)-r\([0-9]*\)$/\1-\3-\2/');;
esac

feeds=/etc/opkg/customfeeds.conf

if [ "$SIGNED" = "1" ] && [ -n "$KEYID" ]; then
  mkdir -p /etc/opkg/keys
  if wget -qO "/etc/opkg/keys/$KEYID" "$BASE_URL/repo.pub"; then
    echo "installed signing key $KEYID"
  else
    echo "warning: could not download repo.pub from $BASE_URL/repo.pub"
  fi
fi

# Remove feeds we added previously. Our lines live between BEGIN/END marker
# comments (opkg ignores whole-line comments; a trailing comment on a src/gz
# line would be rejected as garbage). The second expression also cleans up the
# older format that appended "# openwrt-feed-builder" to each src/gz line.
sed -i '/# openwrt-feed-builder BEGIN/,/# openwrt-feed-builder END/d; /# openwrt-feed-builder/d' "$feeds" 2>/dev/null || true

echo "# openwrt-feed-builder BEGIN (managed block; edits are overwritten)" >> "$feeds"
add_feed() {
  if wget -qO /dev/null "$2/Packages.gz" 2>/dev/null; then
    echo "src/gz $1 $2" >> "$feeds"
    echo "+ $1 -> $2"
    return 0
  fi
  return 1
}
# branch-wide userspace (release-independent sources), one entry per feed dir
# the build actually produced. When Architecture:all packages could not be
# fanned into real arch dirs they live under all/ — probe it as a fallback.
# shellcheck disable=SC2043 # the generated list may hold a single feed
for FEED in @FEEDS@; do
  add_feed "@PREFIX@_${ARCH}_${FEED}" "$BASE_URL/packages-$BRANCH/$ARCH/$FEED" || \
  add_feed "@PREFIX@_all_${FEED}"     "$BASE_URL/packages-$BRANCH/all/$FEED" || true
done
# kmods for this release, keyed by this device's exact kernel
[ -z "$KERNEL" ] || \
  add_feed "@PREFIX@_${ARCH}_kmods"  "$BASE_URL/$RELEASE/targets/$DISTRIB_TARGET/kmods/$KERNEL" || true
# this release's target packages (release-bound userspace, kmods w/o kernel dep)
add_feed "@PREFIX@_${ARCH}_targets"  "$BASE_URL/$RELEASE/targets/$DISTRIB_TARGET/packages" || true
echo "# openwrt-feed-builder END" >> "$feeds"

opkg update
echo "done."
`

// addSHAPKTemplate is add.sh for apk branches (OpenWrt 25.12+): the feed list
// holds packages.adb URLs, the key is a PEM file under /etc/apk/keys/, and the
// kernel version comes from the apk installed database.
const addSHAPKTemplate = `#!/bin/sh
# Auto-generated by openwrt-feed-builder. Adds this custom feed for THIS device,
# pinned to release @RELEASE@ (apk). The feed mirrors the
# downloads.openwrt.org/releases/ layout.
#
# On the router:
#   wget -qO- BASE_URL/@RELEASE@/add.sh | sh
# or with an explicit base URL:
#   wget -qO- .../add.sh | BASE_URL=https://my.host sh
set -e

BASE_URL="${BASE_URL:-@BASE_URL@}"
BRANCH="@BRANCH@"
RELEASE="@RELEASE@"
KEYNAME="@PREFIX@.pem"
SIGNED="@SIGNED@"

# shellcheck disable=SC1091 # the device's release file, present at runtime
[ -r /etc/openwrt_release ] && . /etc/openwrt_release
ARCH="$DISTRIB_ARCH"
[ -n "$ARCH" ] || { echo "cannot detect DISTRIB_ARCH (is this OpenWrt?)"; exit 1; }
[ -z "$DISTRIB_RELEASE" ] || [ "$DISTRIB_RELEASE" = "$RELEASE" ] || \
  echo "warning: device runs $DISTRIB_RELEASE but this feed is for $RELEASE"

# Exact kernel this device runs, from the installed kernel package. Its version
# "6.12.94~<hash>-r1" becomes the kmods/<kernel>/ directory name
# "6.12.94-1-<hash>", same convention as the official kmods feed.
KERNEL=$(sed -n '/^P:kernel$/,/^$/s/^V://p' /lib/apk/db/installed 2>/dev/null | head -n 1)
[ -n "$KERNEL" ] || \
  KERNEL=$(apk list -I kernel 2>/dev/null | sed -n 's/^kernel-\([^ ]*\) .*/\1/p' | head -n 1)
case "$KERNEL" in
  *~*) KERNEL=$(echo "$KERNEL" | sed 's/^\(.*\)~\([0-9a-f]*\)-r\([0-9]*\)$/\1-\3-\2/');;
esac

feeds=/etc/apk/repositories.d/customfeeds.list

if [ "$SIGNED" = "1" ]; then
  mkdir -p /etc/apk/keys
  if wget -qO "/etc/apk/keys/$KEYNAME" "$BASE_URL/@APKPUB@"; then
    echo "installed signing key $KEYNAME"
  else
    echo "warning: could not download @APKPUB@ from $BASE_URL/@APKPUB@"
  fi
fi

# Remove feeds we added previously (our lines live between BEGIN/END marker
# comments; apk ignores # lines in repository files).
sed -i '/# openwrt-feed-builder BEGIN/,/# openwrt-feed-builder END/d' "$feeds" 2>/dev/null || true

echo "# openwrt-feed-builder BEGIN (managed block; edits are overwritten)" >> "$feeds"
add_feed() {
  if wget -qO /dev/null "$1/packages.adb" 2>/dev/null; then
    echo "$1/packages.adb" >> "$feeds"
    echo "+ $1/packages.adb"
    return 0
  fi
  return 1
}
# branch-wide userspace (release-independent sources), one entry per feed dir
# the build actually produced; all/ is probed as a fallback.
# shellcheck disable=SC2043 # the generated list may hold a single feed
for FEED in @FEEDS@; do
  add_feed "$BASE_URL/packages-$BRANCH/$ARCH/$FEED" || \
  add_feed "$BASE_URL/packages-$BRANCH/all/$FEED" || true
done
# kmods for this release, keyed by this device's exact kernel
[ -z "$KERNEL" ] || \
  add_feed "$BASE_URL/$RELEASE/targets/$DISTRIB_TARGET/kmods/$KERNEL" || true
# this release's target packages (release-bound userspace, kmods w/o kernel dep)
add_feed "$BASE_URL/$RELEASE/targets/$DISTRIB_TARGET/packages" || true
echo "# openwrt-feed-builder END" >> "$feeds"

if [ "$SIGNED" = "1" ]; then
  apk update
else
  echo "note: the feed is unsigned; apk needs --allow-untrusted for it"
  apk --allow-untrusted update
fi
echo "done."
`

// writeRepoHelpers writes one release-pinned add.sh per declared point release
// under <output>/<release>/ (opkg or apk flavor by the release's branch), plus
// the public keys at the output root when signed: repo.pub for the opkg
// branches, repo-apk.pem for the apk ones. feeds maps each branch to the
// branch-wide feed dir names the build produced (falling back to the layout
// default), which add.sh probes one by one; keyID is the usign key id.
// Returns the paths of the written scripts.
func writeRepoHelpers(outputDir string, cfg *Config, feeds map[string][]string,
	signed bool, keyID string,
) ([]string, error) {
	if err := os.MkdirAll(outputDir, dirPerm); err != nil {
		return nil, fmt.Errorf("create dir: %w", err)
	}

	layout := cfg.Layout
	formats := toSet(layout.formats())

	for _, pub := range []struct {
		format, src, dst, what string
	}{
		{formatIPK, cfg.Sign.PublicKey, "repo.pub", "sign.public_key"},
		{formatAPK, cfg.Sign.APKPublicKey, apkPubName, "sign.apk_public_key"},
	} {
		if !signed || !formats[pub.format] || pub.src == "" {
			continue
		}

		data, err := os.ReadFile(pub.src)
		if err != nil {
			return nil, fmt.Errorf("cannot read %s: %w", pub.what, err)
		}

		if err := writeFile(filepath.Join(outputDir, pub.dst), data, filePerm); err != nil {
			return nil, err
		}
	}

	var written []string

	for _, release := range layout.Versions {
		branch := releaseBranch(release)

		branchFeeds := feeds[branch]
		if len(branchFeeds) == 0 {
			branchFeeds = []string{orDefault(layout.DefaultFeed, "packages")}
		}

		tmpl := addSHTemplate
		if branchFormat(branch) == formatAPK {
			tmpl = addSHAPKTemplate
		}

		repl := strings.NewReplacer(
			"@BASE_URL@", orDefault(cfg.BaseURL, "http://HOST:PORT"),
			"@BRANCH@", branch,
			"@RELEASE@", release,
			"@PREFIX@", orDefault(cfg.FeedPrefix, "custom"),
			"@FEEDS@", strings.Join(branchFeeds, " "),
			"@KEYID@", keyID,
			"@APKPUB@", apkPubName,
			"@SIGNED@", boolDigit(signed),
		)

		dir := filepath.Join(outputDir, release)
		if err := os.MkdirAll(dir, dirPerm); err != nil {
			return nil, fmt.Errorf("create dir: %w", err)
		}

		addSH := filepath.Join(dir, "add.sh")
		if err := writeFile(addSH, []byte(repl.Replace(tmpl)), execPerm); err != nil {
			return nil, err
		}

		written = append(written, addSH)
	}

	return written, nil
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}

	return s
}

func boolDigit(b bool) string {
	if b {
		return "1"
	}

	return "0"
}
