package feedbuilder

// Generate the repo.pub + add.sh helper files.
//
// One installer script is generated per declared point release, pinned to that
// release: <release>/add.sh inside each release directory, next to targets/.
// repo.pub sits at the output root. The script detects the device's
// architecture, target and exact kernel on its own, installs the signing key,
// and adds only the feeds that actually exist for that device.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const addSHTemplate = `#!/bin/sh
# Auto-generated by openwrt-feed-builder. Adds this custom feed for THIS device,
# pinned to release @RELEASE@. The feed mirrors the
# downloads.openwrt.org/releases/ layout.
#
# On the router:
#   wget -qO- BASE_URL/@RELEASE@/add.sh | sh
# or with an explicit base URL:
#   wget -qO- .../add.sh | BASE_URL=https://my.host sh
set -e

BASE_URL="${BASE_URL:-@BASE_URL@}"
BRANCH="@BRANCH@"
RELEASE="@RELEASE@"
KEYID="@KEYID@"
SIGNED="@SIGNED@"

[ -r /etc/openwrt_release ] && . /etc/openwrt_release
ARCH="$DISTRIB_ARCH"
[ -n "$ARCH" ] || { echo "cannot detect DISTRIB_ARCH (is this OpenWrt?)"; exit 1; }
[ -z "$DISTRIB_RELEASE" ] || [ "$DISTRIB_RELEASE" = "$RELEASE" ] || \
  echo "warning: device runs $DISTRIB_RELEASE but this feed is for $RELEASE"

# Exact kernel this device runs, from the installed kernel package. Its version
# "6.6.141~<hash>-r1" becomes the kmods/<kernel>/ directory name
# "6.6.141-1-<hash>", same convention as the official kmods feed.
KERNEL=$(sed -n '/^Package: kernel$/,/^$/s/^Version: *//p' /usr/lib/opkg/status 2>/dev/null | head -n 1)
case "$KERNEL" in
  *~*) KERNEL=$(echo "$KERNEL" | sed 's/^\(.*\)~\([0-9a-f]*\)-r\([0-9]*\)$/\1-\3-\2/');;
esac

feeds=/etc/opkg/customfeeds.conf

if [ "$SIGNED" = "1" ] && [ -n "$KEYID" ]; then
  mkdir -p /etc/opkg/keys
  if wget -qO "/etc/opkg/keys/$KEYID" "$BASE_URL/repo.pub"; then
    echo "installed signing key $KEYID"
  else
    echo "warning: could not download repo.pub from $BASE_URL/repo.pub"
  fi
fi

# Remove feeds we added previously. Our lines live between BEGIN/END marker
# comments (opkg ignores whole-line comments; a trailing comment on a src/gz
# line would be rejected as garbage). The second expression also cleans up the
# older format that appended "# openwrt-feed-builder" to each src/gz line.
sed -i '/# openwrt-feed-builder BEGIN/,/# openwrt-feed-builder END/d; /# openwrt-feed-builder/d' "$feeds" 2>/dev/null || true

echo "# openwrt-feed-builder BEGIN (managed block; edits are overwritten)" >> "$feeds"
add_feed() {
  if wget -qO /dev/null "$2/Packages.gz" 2>/dev/null; then
    echo "src/gz $1 $2" >> "$feeds"
    echo "+ $1 -> $2"
    return 0
  fi
  return 1
}
# branch-wide userspace (release-independent sources), one entry per feed dir
# the build actually produced. When Architecture:all packages could not be
# fanned into real arch dirs they live under all/ — probe it as a fallback.
for FEED in @FEEDS@; do
  add_feed "@PREFIX@_${ARCH}_${FEED}" "$BASE_URL/packages-$BRANCH/$ARCH/$FEED" || \
  add_feed "@PREFIX@_all_${FEED}"     "$BASE_URL/packages-$BRANCH/all/$FEED" || true
done
# kmods for this release, keyed by this device's exact kernel
[ -z "$KERNEL" ] || \
  add_feed "@PREFIX@_${ARCH}_kmods"  "$BASE_URL/$RELEASE/targets/$DISTRIB_TARGET/kmods/$KERNEL" || true
# this release's target packages (release-bound userspace, kmods w/o kernel dep)
add_feed "@PREFIX@_${ARCH}_targets"  "$BASE_URL/$RELEASE/targets/$DISTRIB_TARGET/packages" || true
echo "# openwrt-feed-builder END" >> "$feeds"

opkg update
echo "done."
`

// writeRepoHelpers writes one release-pinned add.sh per declared point release
// under <output>/<release>/, plus repo.pub at the output root when signed.
// feedPrefix is the opkg feed-name prefix (custom_<arch> style); feeds are the
// branch-wide feed dir names the build produced (falling back to the layout
// default), which add.sh probes one by one. Returns the paths of the written
// scripts.
func writeRepoHelpers(outputDir string, layout Layout, feeds []string,
	baseURL, feedPrefix string, signed bool, keyID, publicKey string) ([]string, error) {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return nil, err
	}

	if signed && publicKey != "" {
		data, err := os.ReadFile(publicKey)
		if err != nil {
			return nil, fmt.Errorf("cannot read sign.public_key: %w", err)
		}
		if err := os.WriteFile(filepath.Join(outputDir, "repo.pub"), data, 0o644); err != nil {
			return nil, err
		}
	}

	if len(feeds) == 0 {
		feeds = []string{orDefault(layout.DefaultFeed, "packages")}
	}

	var written []string
	for _, release := range layout.Versions {
		repl := strings.NewReplacer(
			"@BASE_URL@", orDefault(baseURL, "http://HOST:PORT"),
			"@BRANCH@", layout.Branch,
			"@RELEASE@", release,
			"@PREFIX@", orDefault(feedPrefix, "custom"),
			"@FEEDS@", strings.Join(feeds, " "),
			"@KEYID@", keyID,
			"@SIGNED@", boolDigit(signed),
		)
		dir := filepath.Join(outputDir, release)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, err
		}
		addSH := filepath.Join(dir, "add.sh")
		if err := os.WriteFile(addSH, []byte(repl.Replace(addSHTemplate)), 0o755); err != nil {
			return nil, err
		}
		written = append(written, addSH)
	}
	return written, nil
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}

func boolDigit(b bool) string {
	if b {
		return "1"
	}
	return "0"
}
