package feedbuilder

// Test fixture values shared across the tests.
const (
	tArchA53          = "aarch64_cortex-a53"
	tArchAll          = "all"
	tArchMipsel       = "mipsel_24kc"
	tArchX86          = "x86_64"
	tBranch24         = "24.10"
	tBranch25         = "25.12"
	tDepKmodTun       = "kmod-tun"
	tDepLibc          = "libc"
	tFeedA53          = "packages-24.10/aarch64_cortex-a53/packages"
	tFeedMipsel       = "packages-24.10/mipsel_24kc/packages"
	tFeedPackages     = "packages"
	tFeedPrefix       = "myfeed"
	tFeedX86          = "packages-24.10/x86_64/packages"
	tFieldDepends     = "Depends"
	tFieldPackage     = "Package"
	tInstallX         = "/opt/x"
	tKeyArchMap       = "arch_map"
	tKeyInstall       = "install"
	tKeyTool          = "tool"
	tKeyURL           = "url"
	tLicenseMIT       = "MIT"
	tPkgMihomo        = "mihomo"
	tRel24106         = "24.10.6"
	tRel24107         = "24.10.7"
	tRel24108         = "24.10.8"
	tSubtargetFilogic = "filogic"
	tSubtargetMT7621  = "mt7621"
	tTargetFilogic    = "mediatek/filogic"
	tAssetMipsle      = "mipsle-softfloat"
	tTreeFilogicKmods = "24.10.7/targets/mediatek/filogic/kmods/6.6.141-1-abc"
	tTreeFilogicPkgs  = "24.10.7/targets/mediatek/filogic/packages"
	tTreeMT7621Pkgs   = "24.10.7/targets/ramips/mt7621/packages"
	tTypeBinary       = "binary"
	tTypeGithub       = "github"
	tTypeSDK          = "sdk"
	tUPXBest          = "--best"
	tVersion10        = "1.0"
	tVersion123       = "1.2.3"
	tAssetURL         = "http://e/x.gz"
	tKeyArch          = "arch"
	tKeyName          = "name"
	tKeyType          = "type"
	tRel25124         = "25.12.4"
	tRel25125         = "25.12.5"
	tTargetMT7621     = "ramips/mt7621"
	tTargetMediatek   = "mediatek"
	tAssetArm64       = "arm64"
	tKeyVersion       = "version"
)
